#Jasmine Nelson RedID: 820233707 (cssc2157)
#Ernesto Sanchez RedID: 819323499 (cssc2123)
#
#CS570, Summer 2020
#Professor Leonard
#
#Assignment #1, Write to File Using Threads

#Makefile

all:
		gcc bots.c -o bots -lpthread

clean:
		rm bots bots.o QUOTE.txt
